### ISSUE TITLE
Renaming the main class

### ISSUE THREAD

**Issue by Ludonope** [agnostech/flutter_amplify#1]
I think it would be nice to rename the main cognito class as `AwsAmplifyCognito` or even simply `AmplifyCognito`. The `Flutter` prefix (and even `Aws`) is pretty redundant and adds complexity, when we know that we are working with flutter!

Right now is a good moment to do that change since it's in the very early stage of the development, and not that many people would be impacted.

**Comment by vishal-android-freak** [comment]
Thanks for the suggestion, mate. Makes sense! I'll do it :)
