### ISSUE TITLE
Login with wrong password ios  crashing

### ISSUE THREAD

**Issue by midhilaj-com-06** [agnostech/flutter_amplify#13]
Thread 26: Fatal error: Unexpectedly found nil while unwrapping an Optional value
<br>
Fatal error: Unexpectedly found nil while unwrapping an Optional value: file /Users/user/FlutterHome/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_aws_amplify_cognito-1.0.0+7/ios/Classes/SwiftFlutterAwsAmplifyCognito.swift, line 275
https://github.com/jonsaw/amazon-cognito-identity-dart

**Comment by ibadaboom** [comment]
Posted the fix here : 
https://stackoverflow.com/questions/62508756/when-wrong-user-login-ios-app-is-crashing-and-no-log-displayed-but-in-android-i/62534919#62534919

Please fix the issue for master.

**Comment by orestesgaolin** [comment]
You can check out this branch for some fixes related to that https://github.com/orestesgaolin/flutter_amplify/commits/update-dependencies

**Comment by vishal-android-freak** [comment]
@orestesgaolin mind sharing a quick pull request of the fixes you have done so far? Been off for sometime. Let's fix this and have it working 100% :)

**Comment by orestesgaolin** [comment]
Sure, will try to make PR tomorrow

**Comment by orestesgaolin** [comment]
@vishal-android-freak https://github.com/agnostech/flutter_amplify/pull/15

**Comment by vishal-android-freak** [comment]
@orestesgaolin this is very helpful. Thanks a ton! :)
