### ISSUE TITLE
Timeline?

### ISSUE THREAD

**Issue by justinfargnoli** [agnostech/flutter_amplify#18]
Are there a timelines for the development the libraries which are labeled as, "coming soon"?

**Comment by joekendal** [comment]
@justinfargnoli https://github.com/aws-amplify/amplify-js/issues/1852#issuecomment-641560886

**Comment by justinfargnoli** [comment]
@joekendal are you saying that this is the repo the Amplify team is developing amplify-flutter in, thus the comment you linked it the best notion of a timeline we have for amplify-flutter _or_ are you saying that this library is no longer under active development, so it would be best to use the Amplify team's implementation of amplify-flutter and thus the best notion of a timeline that we have for amplify-flutter is the comment that you linked to?

**Comment by joekendal** [comment]
> @joekendal are you saying that this is the repo the Amplify team is developing amplify-flutter in, thus the comment you linked it the best notion of a timeline we have for amplify-flutter _or_ are you saying that this library is no longer under active development, so it would be best to use the Amplify team's implementation of amplify-flutter and thus the best notion of a timeline that we have for amplify-flutter is the comment that you linked to?

the latter
