### ISSUE TITLE
Target of url does not exist:  import 'package:flutter_aws_amplify_cognito_example/authentication.dart'

### ISSUE THREAD

**Issue by zaidmo123** [agnostech/flutter_amplify#2]
Hi,
I am unable to import the authentication package as the url is incorrect.
As a result, I cannot run the example

![image](https://user-images.githubusercontent.com/9531319/77809598-025a4900-7099-11ea-80be-e01cc02451b4.png)

**Comment by vishal-android-freak** [comment]
Hi, you should see the `authentication.dart` file inside the libs folder of the example

![image](https://user-images.githubusercontent.com/5111523/77817040-e0d77c80-70ed-11ea-930e-b63f026e6a89.png)

Can you check and let me know?

Also, the library to import would be this:

`import 'package:flutter_aws_amplify_cognito/flutter_aws_amplify_cognito.dart';`

I have just made a component by name `Authentication` which is then used inside the `build` method. That doesn't contain the library files

**Comment by zaidmo123** [comment]
Hi Vishal,
I started off with the example on pub.dev which only mentioned changes to main.dart
After your response, I copied the missing authentication.dart into my lib folder from https://github.com/agnostech/flutter_amplify/tree/master/flutter_aws_amplify_cognito/example/lib and added the required dependency **expandable: ^4.1.2** to pubspec.yaml, and ran **package get**. 
Still have the error: **error: The method 'Authentication' isn't defined for the type '_MyAppState'. (undefined_method at [flutterapp1] lib\main.dart:15)**

I am going to try cloning the full project of github now and will see if that works

Update: fixed the issue with the missing AndroidManifest.xml file on the cloned github project  (by overwriting this project's files with a new project). Then has a Gradle Project sync error which I thought I resolved, but more erros appeared.

**Comment by vishal-android-freak** [comment]
Yup. Meanwhile, let me see if that file is missing. This is pretty strange
though :/

**Comment by vishal-android-freak** [comment]
@zaidmo123 I think you are trying this in a separate app of yours? Please follow the instructions mentioned here for a new project https://agnostech.github.io/flutteramplify

**Comment by zaidmo123** [comment]
Hi Vishal,

I managed to get the basic example following the instructions on https://agnostech.github.io/flutteramplify which lead to  https://pub.dev/packages/flutter_aws_amplify_cognito#-installing-tab to work with a couple of modifications.

1. authentication.dart is required in the lib folder (copy authentication.dart from https://github.com/agnostech/flutter_amplify/tree/master/flutter_aws_amplify_cognito/example/lib into your lib folder)

2. On the example main.dart code ( https://pub.dev/packages/flutter_aws_amplify_cognito#-example-tab- ), the 2 packages to import:

```
import 'package:flutter_aws_amplify_cognito/flutter_aws_amplify_cognito.dart';
import 'authentication.dart';

```
3. Add to dependencies in pubspec.yaml: 

```
flutter_aws_amplify_cognito: ^1.0.0+6
expandable: ^4.1.2
```

![image](https://user-images.githubusercontent.com/9531319/77863733-ade3d480-7224-11ea-9515-d835d765308c.png)

I'm good to go with trying to add the other pages and amplify config now
Thanks.
