### ISSUE TITLE
Token is not from a supported provider of this identity pool.

### ISSUE THREAD

**Issue by subhendukundu** [agnostech/flutter_amplify#4]
Trying to add Facebook login with AWS Cognito. After logging using [flutter_facebook_login](https://pub.dev/packages/flutter_facebook_login) I am trying to pass the details to AWS. But its throwing error of
Received error response: com.amazonaws.services.cognitoidentity.model.NotAuthorizedException: Token is not from a supported provider of this identity pool. (Service: null; Status Code: 400; Error Code: NotAuthorizedException; Request ID:xxxxxx-xxxxxx-xxxxx-xxxxxx
What am I doing wrong?
```
@override
  void initState() {
    FlutterAwsAmplifyCognito.initialize().then((UserStatus status) {
      print('status-----------------------');
      print(status); // UserStatus.SIGNED_OUT
    }).catchError((error) {
      print(error);
    });
    super.initState();
  }
_loginWithFB() async{    
    final result = await facebookLogin.logIn(['email']);

    switch (result.status) {
      case FacebookLoginStatus.loggedIn:
        final token = result.accessToken.token;
        final graphResponse = await http.get('https://graph.facebook.com/v2.12/me?fields=name,picture,email&access_token=$token');
        final profile = JSON.jsonDecode(graphResponse.body);
        print(profile); // I get the user details 
        print(token); // I get the token here
        FlutterAwsAmplifyCognito.federatedSignIn(IdentityProvider.FACEBOOK, token)
          .then((FederatedSignInResult result) {
            print('-----------');
            print(result.userStatus);
          }).catchError((error) {
            print(error);
          });
        setState(() {
          userProfile = profile;
          _isLoggedIn = true;
        });
        break;

      case FacebookLoginStatus.cancelledByUser:
        setState(() => _isLoggedIn = false );
        break;
      case FacebookLoginStatus.error:
        setState(() => _isLoggedIn = false );
        break;
    }
  }
```
I am aware of https://stackoverflow.com/questions/56637042/amazon-web-services-aws-cognito-error-token-is-not-from-a-supported-provider but I double checked I am using the right api key. Plus I tried with username and password login which worked. 
Thanks in advance.

**Comment by vishal-android-freak** [comment]
Please check if Facebook login has been enabled for your Userpool. As this error is not related to the library directly, I'll suggest you go through the federated sign in docs :)

**Comment by subhendukundu** [comment]
Ok, I am kind of confused here, so. I added the facebook client id to my identity pool's facebook section, now this started taking the token I am passing. But it's not adding the user to User pool dashboard, is that correct behaviour?
If that is, just one last question, according to [this](https://github.com/zino-app/graphql-flutter/issues/209#issuecomment-598835690) I need a JWT token and as my end goal is to fetch data from AppSyns, the session token I get is as good as the JWT token?
Thank you tho :)

**Comment by vishal-android-freak** [comment]
You can use the `idToken` obtained after signing in. It's a JWT :)

**Comment by subhendukundu** [comment]
Yup, but with facebook it wll be `federatedSignIn`. And with `FlutterAwsAmplifyCognito.federatedSignIn(IdentityProvider.FACEBOOK, token)` it doesn't return a `idToken`. Any docs for this?
Liking at the js [docs](https://aws-amplify.github.io/docs/js/authentication#identity-pool-federation), we can pass the user details as well but FlutterAwsAmplifyCognito
`FlutterAwsAmplifyCognito.federatedSignIn(IdentityProvider.GOOGLE, "token", null, "your_cognito_identity_id")` can take user as an arg?
Then how do we link identity provider to user pool so that we can access `idToken` etc?
