### ISSUE TITLE
Error on signOut

### ISSUE THREAD

**Issue by ViniciusDS** [agnostech/flutter_amplify#5]
/// Signs out the user from the current application.
  static Future<void> signOut() async {
    try {
      await _methodChannel.invokeMethod("signOut");
    } on PlatformException catch (e) {
      return Future.error(e);
    }
  }

Lack of return in the method: _methodChannel

**Comment by vishal-android-freak** [comment]
Thank you for pointing it out :) Will fix it ASAP!
