### ISSUE TITLE
Error in android release mode

### ISSUE THREAD

**Issue by krunduev** [agnostech/flutter_amplify#6]
Authorization in debug mode working fine. 

But in release I have: 

Error fetching user details,
Failed to initialize Cognito identity;
please check your awsconfiguration.json 

Internet permission is added to manifest.
`<uses-permission android:name="android.permission.INTERNET"/>
`

**Comment by krunduev** [comment]
![image](https://user-images.githubusercontent.com/644556/78499836-c2abf500-775b-11ea-898c-8b740ca1bf03.png)

**Comment by vishal-android-freak** [comment]
Can you share your awsconfiguration file?

**Comment by kukuandroid** [comment]
@vishal-android-freak  Hello, i'm facing the same issue. All setups has been done as documented.

Here is my awsconfiguration.json

```


{
  "UserAgent": "aws-amplify-cli/0.1.0",
  "Version": "0.1.0",
  "IdentityManager": {
    "Default": {}
  },
  "CredentialsProvider": {
    "CognitoIdentity": {
      "Default": {
        "PoolId": "us-east-1:732ebec2-4bfd-41ea-aae0-d3f956854c7a",
        "Region": "us-east-1"
      }
    }
  },
  "CognitoUserPool": {
    "Default": {
      "PoolId": "us-east-1_bwqd0LYbD",
      "AppClientId": "2p8g85ufl9q6e14imscrr0qveu",
      "AppClientSecret": "15ubhml28rsj51r9i8hogcvvbtc1mqdlers3pjsn2ebntb6rbfle",
      "Region": "us-east-1"
    }
  },
  "Auth": {
    "Default": {
      "authenticationFlowType": "USER_SRP_AUTH"
    }
  }
}


```

**Comment by kukuandroid** [comment]
@krunduev  did you found a solution  ?

**Comment by krunduev** [comment]
Unfortunately no, just postpone this task.

My awsconfiguration:
```
{
    "UserAgent": "aws-amplify-cli/0.1.0",
    "Version": "0.1.0",
    "IdentityManager": {
        "Default": {}
    },
    "CredentialsProvider": {
        "CognitoIdentity": {
            "Default": {
                "PoolId": "eu-west-2:de6ce32e-d6d1-4501-a063-bc70bd94272a",
                "Region": "eu-west-2"
            }
        }
    },
    "CognitoUserPool": {
        "Default": {
            "PoolId": "eu-west-2_8rYJoA8vB",
            "AppClientId": "XXXXXXXXXXXX",
            "AppClientSecret": "XXXXXXXXXXXXXXXXXXXX",
            "Region": "eu-west-2"
        }
    }
}
```

**Comment by orestesgaolin** [comment]
I have the same issue in release mode. I was trying to understand what's happening, updated the Android library to the newest version, check several times if configuration file is actually available in the apk, and everything seems to be fine. But, either way, in release mode I get this error:

> Error fetching user details, Failed to initialize Cognito Userpool; please check your awsconfiguration.json

**Comment by NassB** [comment]
I was having the same problem, so I turn minifyEnabled and shrinkResources to false for my release build :

```
    buildTypes {
        release {
            debuggable false
            minifyEnabled false
            shrinkResources false
            signingConfig signingConfigs.release
        }
        debug {
            signingConfig signingConfigs.debug
        }
    }
```

And I was able to sign in in my release app.

Hope this help.

**Comment by krunduev** [comment]
Yes, this works for me too!

**Comment by orestesgaolin** [comment]
The issue here is related to missing proguard rules. Disabling minification is not a good solution, because it is applied to all your plugins.

You can fix this by using following proguard-rules.pro:

```
## Flutter wrapper
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.**  { *; }
-keep class io.flutter.util.**  { *; }
-keep class io.flutter.view.**  { *; }
-keep class io.flutter.**  { *; }
-keep class io.flutter.plugins.**  { *; }
-dontwarn io.flutter.embedding.**

-keepnames class com.amazonaws.**
-keepnames class com.amazon.**
-keepnames class com.amazonaws.mobile.**
-keepnames class com.amazonaws.mobile.config.**
# Request handlers defined in request.handlers
-keep class com.amazonaws.services.**.*Handler
# The following are referenced but aren't required to run
-dontwarn com.fasterxml.jackson.**
-dontwarn org.apache.commons.logging.**
# Android 6.0 release removes support for the Apache HTTP client
-dontwarn org.apache.http.**
# The SDK has several references of Apache HTTP client
-dontwarn com.amazonaws.http.**
-dontwarn com.amazonaws.metrics.**
-dontwarn com.amazonaws.mobileconnectors.**
```

**Comment by NassB** [comment]
Ok, thank you for the solution. So do I need to disable R8 from gradle.properties if I add proguard-rules.pro ?

```
org.gradle.jvmargs=-Xmx1536M
android.enableR8=true
android.useAndroidX=true
android.enableJetifier=true
```

**Comment by orestesgaolin** [comment]
No, you don't need to disable R8

**Comment by NassB** [comment]
> No, you don't need to disable R8

Thank you!

**Comment by vishal-android-freak** [comment]
Will update the documentation to reflect this. Thanks :)

**Comment by ch-muhammad-adil** [comment]
> I was having the same problem, so I turn minifyEnabled and shrinkResources to false for my release build :
> 
> ```
>     buildTypes {
>         release {
>             debuggable false
>             minifyEnabled false
>             shrinkResources false
>             signingConfig signingConfigs.release
>         }
>         debug {
>             signingConfig signingConfigs.debug
>         }
>     }
> ```
> 
> And I was able to sign in in my release app.
> 
> Hope this help.

This has resolved the issue but now SignIn is not working.

**Comment by ch-muhammad-adil** [comment]
It is giving me this error, `Error getting user attributes, Operation requires a signed-in state` I have noticed my sign in worked fine. Sign in callback is happened.
